# @see https://www.keycloak.org/getting-started/getting-started-docker

services:
  keycloak:
    #image: quay.io/keycloak/keycloak:latest
    build:
      context: .
      args:
        KC_CACHE: ${KC_CACHE:-local}
        KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED:-true}
        KC_DB: ${KC_DB:-postgres}
        KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://postgres:5432/keycloak}
        # bug https://github.com/keycloak/keycloak/issues/25010
        KC_DB_USERNAME: ${KC_DB_USERNAME:-postgres}
        KC_DB_PASSWORD: ${KC_DB_PASSWORD:-postgres}
        KC_HOSTNAME: ${KC_HOSTNAME:-keycloak.loc}
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: keycloak
    restart: unless-stopped
    #command: ["start-dev"]
    command: 
      - "start"
      - "--optimized"
    environment:
      KC_CACHE: ${KC_CACHE:-local}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED-true}
      KC_DB: ${KC_DB:-postgres}
      KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://postgres:5432/keycloak}
      # bug https://github.com/keycloak/keycloak/issues/25010
      KC_DB_USERNAME: ${KC_DB_USERNAME:-postgres}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-postgres}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-keycloak}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-keycloak}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-keycloak.loc}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT:-true}
      KC_HTTP_ENABLED: ${KC_HTTP_ENABLED:-true}
      KC_PROXY_HEADERS: ${KC_PROXY_HEADERS:-xforwarded}
      # RabbitMQ
      KK_TO_RMQ_URL: ${KK_TO_RMQ_URL:-rabbitmq}
      KK_TO_RMQ_PORT: ${KK_TO_RMQ_PORT:-5672}
      KK_TO_RMQ_VHOST: ${KK_TO_RMQ_VHOST:-keycloak}
      KK_TO_RMQ_EXCHANGE: ${KK_TO_RMQ_EXCHANGE:-keycloak}
      KK_TO_RMQ_USERNAME: ${KK_TO_RMQ_USERNAME:-rabbitmq}
      KK_TO_RMQ_PASSWORD: ${KK_TO_RMQ_PASSWORD:-rabbitmq}
      KK_TO_RMQ_USE_TLS: ${KK_TO_RMQ_USE_TLS:-false}
    healthcheck:
      test: curl --fail --silent http://localhost:8080/health || exit 1
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 3s
    networks:
      - keycloak
      - mail
      - postgres

networks:
  keycloak:
    external: true
  mail:
    external: true
  postgres:
    external: true
