version: '3.8'

# @see https://www.keycloak.org/getting-started/getting-started-docker

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    #command: ["start-dev"]
    command: ["start"]
    environment:
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://postgres:5432/keycloak}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-postgres}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-postgres}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-keycloak}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-keycloak}
    healthcheck:
      test: curl --fail --silent http://localhost:8080/health || exit 1
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 3s
    networks:
      - keycloak
      - mail
      - postgres

networks:
  keycloak:
    external: true
  mail:
    external: true
  postgres:
    external: true
