version: '3.8'

# docker network create traefik

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      # Enables the web UI
      - "--api.insecure=true"
      # Enable ping for healthcheck
      - "--ping=true"
      # Enables docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
      # Docker network to use for connections to all containers
      - "--providers.docker.network=traefik"
      # Traefik will listen to incoming request on the port 80 (HTTP)
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # Traefik will listen to incoming request on the port 443 (HTTPS)
      - "--entrypoints.websecure.address=:443"
      # Traefik dynamic configuration
      - "--providers.file.directory=/traefik-config"
      - "--providers.file.watch=true"
    environment:
      TRAEFIK_DOMAIN: ${TRAEFIK_DOMAIN:-traefik.loc}
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: traefik healthcheck --ping
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 3s
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/:/traefik-config:ro,cached
      - ./certs/:/traefik-certs:ro,cached
    networks:
      - traefik

networks:
  traefik:
    name: ${TRAEFIK_DOCKER_NETWORK:-traefik}
    external: true
