# docker network create mail

services:
  mail:
    image: bytemark/smtp:latest
    container_name: mail
    restart: unless-stopped
    networks:
      - mail

networks:
  mail:
    external: true
    name: ${MAIL_DOCKER_NETWORK:-mail}
