# https://taskfile.dev

version: '3'

dotenv: [ '.task-env' ]

vars:
    COMPOSE_FILE: "{{.DOCKER_COMPOSE_FILE}}"

includes:
    docker: ./run/DockerTasks.yml
    keycloak: ./run/KeycloakTasks.yml

tasks:
