# docker network create postgres

services:
  postgres:
    #image: postgres:16
    build: .
    container_name: postgres
    restart: unless-stopped
    shm_size: 1gb
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
      TZ: ${POSTGRES_TIMEZONE:-Europe/Prague}
    healthcheck:
      test: pg_isready -U "postgres" -h 127.0.0.1 -p 5432
      interval: 30s
      retries: 3
      start_period: 20s
      timeout: 3s
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - postgres

volumes:
  postgres-data:

networks:
  postgres:
    external: true
    name: ${POSTGRES_DOCKER_NETWORK:-postgres}
